CS3219-AY2324S1/ay2324s1-course-assessment-g32

- backend/server/controllers/authController.js
- backend/server/services/userService.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/App.test.js
- frontend/src/css/Auth.css
- frontend/src/index.js
- frontend/src/pages/Landing/Landing.css
- frontend/src/pages/Landing/Landing.js
- frontend/src/pages/Login.js
- frontend/src/pages/Signup.js
- Add Login and Signup frontend
- Use Axios, a third party library, to connect frontend to the REST API
- Add a Global CSS folder for css files that are commonly used throughout the app
- Closes #17, #18
> Add Login and Signup frontend, and connect to the API

- README.md
- backend/server.js
- backend/server/controllers/authController.js
- backend/server/repositories/userRepoMySql.js
- backend/server/services/userService.js
Integrate MySQL query calling method into existing C-S-R model.
Implement createUser to add to MySQL database.
> Implement MySQL-based user storage

- README.md
- backend/server.js
- backend/server/controllers/authController.js
- backend/server/repositories/userRepoMySql.js
- backend/server/routes/test.js
- backend/server/services/userService.js
- POST to `/test/getUserInfo`
- Provide `id` or `email`
- POST to `/test/update`
- Provide `id` and (`username` and/or `password`)
- POST to `/test/deregister`
- Provide `id`
Closes #21.
> Implement getUserInfo, updateUser and deleteUser

- backend/server/controllers/authController.js
- backend/server/repositories/userRepoMySql.js
- backend/server/services/userService.js
When login cred are correct, expected json result should look something like this
```
{
"message": "User logged in successfully",
"id": 17
}
```
> Bugfix: Fix the issue preventing a proper login

- backend/server/repositories/questionRepository.js
- backend/server/services/questionService.js
- frontend/src/components/CreateQuestion/CreateQuestion.js
- frontend/src/components/EditQuestion.js
- frontend/src/utils/toast.js
> Prevent duplicate title when editing/creating questions

- backend/server/repositories/questionRepository.js
- backend/server/services/questionService.js
- frontend/src/api/QuestionApi.js
> Update code quality for Assignment 1

- backend/server/services/questionService.js
- frontend/src/api/QuestionApi.js
- frontend/src/components/Question/CreateQuestion/CreateQuestion.js
- frontend/src/components/Question/EditQuestion.js
- frontend/src/components/Question/QuestionDescription/QuestionDescription.js
- frontend/src/components/Question/QuestionList.js
- frontend/src/pages/Landing/Landing.js
- frontend/src/pages/ManageUserProfiles/ManageUserProfiles.js
- frontend/src/pages/UserProfile/UserProfile.js
- frontend/src/utils/toast.js
- Resolve bug of multiple same toast appearing
- Add handling of server connection errors and generic messages
> Update code from assignment 1 onto assignment 2

- backend/server/services/userService.js
- frontend/src/api/UserApi.js
- frontend/src/components/User/ChangeUserPassword.js
- frontend/src/components/User/EditUser.js
- frontend/src/components/User/UserList/UserList.js
- frontend/src/components/User/ViewUser.js
- frontend/src/pages/Login.js
- frontend/src/pages/Signup.js
- frontend/src/pages/UserProfile/UserProfile.js
- frontend/src/utils/toast.js
1. Add error handling in `frontend/UserAPI`. 
Resolves #70 .
2. Resolve bug in previously allowing updating password of length < 8. 
Resolves #72 .
4. Remove eslint warnings for generic throws in `backend/userService`.
> Add error handling in UserAPI, resolve bug, remove eslint

- README.md
- package-lock.json
- package.json
To install all dependencies of both FE and BE: `npm install-all`
To start the whole app (aka both FE and BE): `npm start-all`
> Add commands to run all services from parent package

- .github/workflows/ci.yml
- frontend/src/api/QuestionApi.js
- frontend/src/api/UserApi.js
- frontend/src/loadEnvironment.js
- template.env
> Read variable server URL  from .env 

- backend/server.js
- frontend/src/components/User/AddUser.js
- frontend/src/components/User/UserList/UserList.js
- package-lock.json
- package.json
> Change Add user to Register user on UI

- backend/server/services/userService.js
- frontend/src/components/ConfirmationWindow/ConfirmationWindows.js
- frontend/src/components/Question/CreateQuestion/CreateQuestion.js
- frontend/src/components/Question/EditQuestion.js
- frontend/src/components/Question/QuestionDescription/QuestionDescription.js
- frontend/src/components/Question/QuestionList.js
- frontend/src/components/User/AddUser.js
- frontend/src/components/User/ChangeUserPassword.js
- frontend/src/components/User/EditUser.js
- frontend/src/components/User/UserList/UserList.js
- frontend/src/components/User/ViewUser.js
- frontend/src/pages/Login.js
- frontend/src/pages/ManageUserProfile/ManageUserProfile.js
- frontend/src/pages/Signup.js
- frontend/src/utils/errors.js
- frontend/src/utils/toast.js
Addition:
- Add a confirmation window before the user is allowed to deregister an account
- Add back buttons to certain Account components
Bug fixed:
- UserList not reloading after creating an account
- Caught unhandled server errors
Improvements:
- Extract all error handling to a new core function errorHandler (src/utils/errors.js)
> Require user's confirmation for critical actions

- README.md
- backend/package-lock.json
- backend/package.json
- backend/server.js
- backend/server/controllers/queueController.js
- backend/server/routes/queue.js
- backend/server/services/matchService.js
- backend/server/services/queueService.js
- backend/server/services/userService.js
- frontend/src/components/ConfirmationWindow/ConfirmationWindows.js
- frontend/src/components/Question/CreateQuestion/CreateQuestion.js
- frontend/src/components/Question/EditQuestion.js
- frontend/src/components/Question/QuestionDescription/QuestionDescription.js
- frontend/src/components/Question/QuestionList.js
- frontend/src/components/User/AddUser.js
- frontend/src/components/User/ChangeUserPassword.js
- frontend/src/components/User/EditUser.js
- frontend/src/components/User/UserList/UserList.js
- frontend/src/components/User/ViewUser.js
- frontend/src/pages/Login.js
- frontend/src/pages/ManageUserProfile/ManageUserProfile.js
- frontend/src/pages/Signup.js
- frontend/src/utils/errors.js
- frontend/src/utils/toast.js
Instructions can be found in README `Temporary Setup for Assignment 5`
Things set up:
- 3 different queues for different difficulty level
- Able to see which client match with who in command prompt
Things to work on:
- Move the services to appropriate directories (?)
- Queue is responding to the client instantly without waiting for matching service to match (Might need to create another queue for matching service to respond back to queueing service)
> Implement backend for RabbitMQ queue and match service

- backend/server/controllers/queueController.js
- backend/server/services/matchService.js
- backend/server/services/queueService.js
Backend for matching and queueing service is completed.
Need to adjust response body depending on client's requirement.
> Allow matching/queueing service to respond to client

- backend/server/controllers/queueController.js
- backend/server/routes/queue.js
- backend/server/services/matchService.js
- backend/server/services/queueService.js
- frontend/src/App.js
- frontend/src/api/QueueApi.js
- frontend/src/components/MatchMaking/Queue.js
- frontend/src/components/MatchMaking/SelectComplexity.js
- frontend/src/pages/MatchMaking/MatchMaking.js
Also added ability to exit a queue, and fix timeout issues if Matching Service is switched off.
> Add wireframe UI/UX for Queueing/Matching Service

- backend/server/services/matchService.js
- frontend/src/components/MatchMaking/MatchingModal.js
- frontend/src/components/MatchMaking/Queue.js
Make user leave queue when modal is closed, or page is refreshed.
Add frontend 32 seconds (2 seconds buffer) timer in the event if the backend fails to respond, else the frontend will be waiting indefinitely.
Fix bug where modal shows Easy complexity state even though user is on Medium/Hard complexity.
> Assignment 5 bug fixes

- frontend/src/components/Header.js
- frontend/src/utils/MaintainerRoute.js
Prevent them from accessing the unauthorised webpage
Closes #103
> Remove "Manage User Profiles" button for non-maintainer users

- .github/workflows/ci.yml
- frontend/src/pages/Login.js
Tested the app too, seems like theres no bugs
> Remove comments

- backend/server.js
- frontend/src/components/Collaboration/Chat.js
- frontend/src/components/Collaboration/LiveCode.js
- frontend/src/components/MatchMaking/MatchingModal.js
- frontend/src/pages/Collaboration/Collaboration.js
- Allow 2 users in the same room to see what they are typing live.
- Modularized Chat and LiveCoding into separate components, so that Collaboration page can use them as elements instead.
> Implement live collaboration coding space

- backend/server/controllers/userController.js
- backend/server/routes/user.js
- backend/server/services/userService.js
- frontend/src/App.js
- frontend/src/api/QuestionApi.js
- frontend/src/components/Question/QuestionList.js
- frontend/src/pages/User/UsersManagement/AddUser.js
This PR implemented the following:
1) Admin is able to delete questions
2) Admin is able to create users
- Merge createUser into signup as creating a user does not require the user to be a maintainer
3) Fix bug where multiple accounts can be registered with the same email
4) Only maintainers are able to see the "Create Question" button
TODO:
1) Checking that all the functionalities work (via FE and Postman)
- Make sure the correct toast is showing
- Log any errors or info if needed (log the correct ones)
2) Create Question API to send API request to AuthorizeMaintainer endpoint first
> Assignment 3

- README.md
- backend/server/services/userService.js
- frontend/src/loadEnvironment.js
- template.env
This PR
- Update README.md
- Correct comment in the code
- Update env variables
> Assignment 3 README.md and Comment and env corrections

- Question/src/QuestionServer.js
- User/src/UserServer.js
- For user service: Added attempts to connect to MySQL db before stopping the docker container if MySQL db is not running
- For question service: Added code to stop question service container if cannot connect to Mongo atlas
> Modified user and question services on how they deal with failures when connecting to db

- frontend/src/components/Question/QuestionList.js
- frontend/src/components/User/UserList.js
Move "Add Question" and "Add User" buttons to top of page, so they do not need to scroll all the way down for the action
> Improve UX for maintainer

- frontend/src/css/Auth.css
- frontend/src/pages/Login.js
- frontend/src/pages/Signup.js
- frontend/src/pages/UnauthorizedPage.js
* add `autoComplete` to hint the type of input field
* add `autoFocus` to login and signup pages, so user can quickly fill up the form without needing to move the mouse to click on the input.
* add local form validation for ensure fields are complete before query to server.
> Improve UX

- Collaboration/src/CollaborationServer.js
- frontend/src/components/Collaboration/Chat.js
- frontend/src/components/Collaboration/CodeEditor.js
- frontend/src/css/Chat.css
- frontend/src/pages/Collaboration.js
This PR consists of adding Chat related functionalities:
- Broadcasting to chat whenever a user changes a question/language
- Auto-scroll to bottom of chat, whenever a new message is received
- Enable 'enter' button to send message instead of solely via 'send button'
Closes #239
> Add chat related functionality

- Auth/src/AuthController.js
- Execution/src/ExecutionController.js
- History/src/HistoryController.js
- History/src/HistoryRepository.js
- History/src/HistoryService.js
- Question/src/QuestionController.js
- Question/src/QuestionRepository.js
- Question/src/QuestionService.js
- User/src/UserController.js
- User/src/UserModel.js
- User/src/UserRepository.js
- User/src/UserService.js
Inline module exports to allow cleaner code maintenance when renaming function names.
Mainly done for controller-service-repository pattern.
The following services were affected:
User, Question, History, Execution, Auth
> Inline module exports

- README.md
- docs/ApiEndpoints.md
- docs/Containerization.md
- docs/LocalHosting.md
- docs/LocalRabbitMqSetup.md
- docs/TestAccounts.md
See [GHFM alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts)
> Improve docs

- History/src/HistoryController.js
- History/src/HistoryRoutes.js
- History/src/helpers/callsToQuestion.js
- Question/src/QuestionRepository.js
- Question/src/QuestionRoutes.js
- User/src/UserRepository.js
- User/src/UserRoutes.js
- User/src/UserService.js
- docs/ApiEndpoints.md
- frontend/src/api/QuestionApi.js
- frontend/src/api/UserApi.js
Update names of endpoints. Closes #118.
Also updated API endpoints documentation for missing/outdated endpoints.
Fix bugs introduced in previous commits.
> Update API endpoints names

- frontend/src/components/MatchMaking/Queue.js
> Add retry functionality for matching service

- compose.yml
- template.env
http://localhost:3000 -> http://localhost
the same should goes for deployment
> Remove the need for port 3000 on URL

- frontend/src/components/Question/QuestionContent.js
- frontend/src/components/Question/QuestionList.js
- frontend/src/components/Question/index.js
- frontend/src/components/SubmissionHistory/SubmissionList.js
- frontend/src/components/User/UserList.js
Bugfix: resolve table page length bug
> Bugfix: resolve table page length bug
